language: cpp
compiler: gcc
env:
  global:
  - secure: "VwaW/I3Sp1lxYf5s1cdqSo11jFa6BBuanjqbkfSLLAiZoSvXiXIb0bGAjWcOw5KYm2sxJfZCdsBsvI0z2P7yBE1NYP8hFHgKiglhi2grfRdhyBZAThbBKZZ41CU1xXoDeH0ZRC9eZHmVTwOZLe8RoBhE7v3gctu4wbmEh/4Miqk="
  - ROS_DISTRO=hydro
notifications:
  email:
  - hpp-source@laas.fr
branches:
  only:
  - master
  - hydro
  - groovy
  - fuerte
  - catkin
  - travis
before_install: ./.travis/run dependencies/catkin; ./.travis/run before_install
script: ./.travis/run build
after_success: ./.travis/run after_success
after_failure: ./.travis/run after_failure
